### PR TITLE
Added window_classrole_blacklist for class.role blacklisting

### PR DESCRIPTION
**Pull request by erenfro**
This gets around the specific issue of Tilix in quake mode, while opening the door to more possible blacklist combinations.

### CODE REVIEW

**Comment by DimseBoms** [comment]
These are nice additions. I will merge this right away :)

I reckon I'll have to move the blacklists to a config file that is properly documented some time in the future, unless there is a better solution to this issue.

**Comment by erenfro** [comment]
Thanks! And, I'm looking further into things as well, still, because just handling sticky alone likely omits a lot of the blacklist you already had, potentially. Maybe not all, but a good lot. And understanding specific window's classes and roles and not just relying purely on the name (which can change, in various ways, dynamically).

**Comment by DimseBoms** [comment]
Yeah, you're right about that. What command did you use to get this https://github.com/DimseBoms/XFCE-Dynamic-Workspace/issues/2#issuecomment-1546711552 information

**Comment by erenfro** [comment]
wmctrl -l to list (usually good, not always gets everything)
xprop -root _NET_ACTIVE_WINDOW (gets WID of a terminal easily.)
sleep 5 && echo `xdotool getactivewindow`  (Gets WID of any active window after sleep passes it on)

xwininfo -id <WID>
xprop -id <WID> (this is the most informative, including class, role, sticky, etc)

**Pull request merged**
